Separating the routing mechanism into a separate middleware
zf-fr/zfr-eb-worker pull request #59
Opened 2017-11-22 11:39 UTC by benomite

Separating the routing mechanism into a separate middleware, so that you can pipe middlewares in between that handles these edge cases:

```
// Validates worker request and extracts message attributes
$pipeline->pipe(WorkerMiddleware::class); 

// Here you can optionally pipe additional middlewares in between, for instance:
$pipeline->pipe(IdentifyAwsInternalEventsMiddleware::class);

// Routes to a specific handler based on message name
$pipeline->pipe(MessageRouterMiddleware::class);
```

2017-11-22 15:28 UTC, danizord requested changes
Looks good! Though for BC reason we can't remove this behavior from `WorkerMiddleware`. I'd suggest the following:

* Extract the remaining logic from `WorkerMiddleware` to a new `WorkerMessageAttributesMiddleware`
* Refactor `WorkerMiddleware` to compose both `WorkerMessageAttributesMiddleware` and `WorkerMessageRouterMiddleware`, so that it does not break for existing users.

What do you think?

2017-11-22 15:28 UTC, danizord commented on src/Middleware/MessageRouterMiddleware.php
> +            $response = $response->withStatus(200);
The status code normalization and `X-Handled-By` header could stay in `WorkerMiddleware` since they are unrelated to routing.

2017-11-23 07:26 UTC, benomite commented
I haven't thought about back compatibility -__-'
I'll work on your suggestions, it's a good idea.

2017-11-23 08:14 UTC, benomite commented
I'm struggling here. Do you have an idea on how to properly pipe the 2 new middlewares (WorkerMessageAttributesMiddleware and MessageRouterMiddleware) within the call of WorkerMiddleware ?

2017-11-24 17:14 UTC, danizord commented
@benomite you can require https://github.com/zendframework/zend-stratigility and use it internally for now. In next major release (probably when PSR-15 gets approved) we'll drop it :)

2017-11-27 08:42 UTC, benomite commented
@danizord zend-stratigility require a version of http-interop/http-middleware to be required in composer.json. I've drop this, user may choose the version they are compatible with (0.5.0 or 0.4.3). This may be a bad practice, what do you think?

2017-12-01 18:49 UTC, danizord reviewed
Sorry for delay. We had lots of changes in PSR-15/Stratigility/Expressive stuff last week and I wanted to wait before taking a decision on this one.

In short, we can release zfr-eb-worker 6.2 supporting both http-middleware ^0.4 and ^0.5 + separate message router. When installing the package, Composer will ask the consumer which version to use, unless it is already specified in root composer.json.

Then I'll work on next major (7.0) version supporting PSR-15 when it gets approved, but it's only expected to happen at January 2018.

2017-12-01 18:49 UTC, danizord commented on src/Middleware/WorkerMiddleware.php
> +    public function __construct(ContainerInterface $container)
That's a BC break. We should use this param to instantiate the `WorkerMessageRouterMiddleware` internally.

2017-12-18 14:51 UTC, benomite commented
Hi!
Any updates on this?
Thanks!

2017-12-19 02:27 UTC, merged

2017-12-19 02:29 UTC, danizord commented
Thanks @benomite and @wysow! I'm gonna prepare a new release this week :)